// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: FlowService.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoveFlowReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlowId string `protobuf:"bytes,1,opt,name=flowId,proto3" json:"flowId,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *RemoveFlowReq) Reset() {
	*x = RemoveFlowReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FlowService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFlowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFlowReq) ProtoMessage() {}

func (x *RemoveFlowReq) ProtoReflect() protoreflect.Message {
	mi := &file_FlowService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFlowReq.ProtoReflect.Descriptor instead.
func (*RemoveFlowReq) Descriptor() ([]byte, []int) {
	return file_FlowService_proto_rawDescGZIP(), []int{0}
}

func (x *RemoveFlowReq) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *RemoveFlowReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveFlowResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveFlowResp) Reset() {
	*x = RemoveFlowResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FlowService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFlowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFlowResp) ProtoMessage() {}

func (x *RemoveFlowResp) ProtoReflect() protoreflect.Message {
	mi := &file_FlowService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFlowResp.ProtoReflect.Descriptor instead.
func (*RemoveFlowResp) Descriptor() ([]byte, []int) {
	return file_FlowService_proto_rawDescGZIP(), []int{1}
}

type UpdateFlowReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flow   *Flow  `protobuf:"bytes,1,opt,name=flow,proto3" json:"flow,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *UpdateFlowReq) Reset() {
	*x = UpdateFlowReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FlowService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFlowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlowReq) ProtoMessage() {}

func (x *UpdateFlowReq) ProtoReflect() protoreflect.Message {
	mi := &file_FlowService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlowReq.ProtoReflect.Descriptor instead.
func (*UpdateFlowReq) Descriptor() ([]byte, []int) {
	return file_FlowService_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateFlowReq) GetFlow() *Flow {
	if x != nil {
		return x.Flow
	}
	return nil
}

func (x *UpdateFlowReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateFlowResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateFlowResp) Reset() {
	*x = UpdateFlowResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FlowService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFlowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlowResp) ProtoMessage() {}

func (x *UpdateFlowResp) ProtoReflect() protoreflect.Message {
	mi := &file_FlowService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlowResp.ProtoReflect.Descriptor instead.
func (*UpdateFlowResp) Descriptor() ([]byte, []int) {
	return file_FlowService_proto_rawDescGZIP(), []int{3}
}

type NewFlowReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flow   *Flow  `protobuf:"bytes,1,opt,name=flow,proto3" json:"flow,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *NewFlowReq) Reset() {
	*x = NewFlowReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FlowService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewFlowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewFlowReq) ProtoMessage() {}

func (x *NewFlowReq) ProtoReflect() protoreflect.Message {
	mi := &file_FlowService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewFlowReq.ProtoReflect.Descriptor instead.
func (*NewFlowReq) Descriptor() ([]byte, []int) {
	return file_FlowService_proto_rawDescGZIP(), []int{4}
}

func (x *NewFlowReq) GetFlow() *Flow {
	if x != nil {
		return x.Flow
	}
	return nil
}

func (x *NewFlowReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type NewFlowResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewFlowResp) Reset() {
	*x = NewFlowResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FlowService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewFlowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewFlowResp) ProtoMessage() {}

func (x *NewFlowResp) ProtoReflect() protoreflect.Message {
	mi := &file_FlowService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewFlowResp.ProtoReflect.Descriptor instead.
func (*NewFlowResp) Descriptor() ([]byte, []int) {
	return file_FlowService_proto_rawDescGZIP(), []int{5}
}

type GetFlowListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Keyword     string `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	CurrentPage int32  `protobuf:"varint,3,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	PageSize    int32  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *GetFlowListReq) Reset() {
	*x = GetFlowListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FlowService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlowListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlowListReq) ProtoMessage() {}

func (x *GetFlowListReq) ProtoReflect() protoreflect.Message {
	mi := &file_FlowService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlowListReq.ProtoReflect.Descriptor instead.
func (*GetFlowListReq) Descriptor() ([]byte, []int) {
	return file_FlowService_proto_rawDescGZIP(), []int{6}
}

func (x *GetFlowListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFlowListReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetFlowListReq) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetFlowListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetFlowListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flows []*Flow `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
	Total int32   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetFlowListResp) Reset() {
	*x = GetFlowListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FlowService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlowListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlowListResp) ProtoMessage() {}

func (x *GetFlowListResp) ProtoReflect() protoreflect.Message {
	mi := &file_FlowService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlowListResp.ProtoReflect.Descriptor instead.
func (*GetFlowListResp) Descriptor() ([]byte, []int) {
	return file_FlowService_proto_rawDescGZIP(), []int{7}
}

func (x *GetFlowListResp) GetFlows() []*Flow {
	if x != nil {
		return x.Flows
	}
	return nil
}

func (x *GetFlowListResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_FlowService_proto protoreflect.FileDescriptor

var file_FlowService_proto_rawDesc = []byte{
	0x0a, 0x11, 0x46, 0x6c, 0x6f, 0x77, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x66, 0x6c, 0x6f, 0x77, 0x1a, 0x10, 0x66, 0x6c, 0x6f, 0x77, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x0d, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x6c, 0x6f, 0x77, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6c,
	0x6f, 0x77, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x10, 0x0a, 0x0e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x22, 0x47,
	0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x12,
	0x1e, 0x0a, 0x04, 0x66, 0x6c, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x04, 0x66, 0x6c, 0x6f, 0x77, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x22, 0x44, 0x0a, 0x0a, 0x4e, 0x65, 0x77,
	0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x04, 0x66, 0x6c, 0x6f, 0x77, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x46, 0x6c, 0x6f,
	0x77, 0x52, 0x04, 0x66, 0x6c, 0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x0d, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x22, 0x80,
	0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x22, 0x49, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x46, 0x6c, 0x6f, 0x77, 0x52,
	0x05, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x32, 0xeb, 0x01, 0x0a,
	0x0b, 0x46, 0x6c, 0x6f, 0x77, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x07,
	0x4e, 0x65, 0x77, 0x46, 0x6c, 0x6f, 0x77, 0x12, 0x10, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x4e,
	0x65, 0x77, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x66, 0x6c, 0x6f, 0x77,
	0x2e, 0x4e, 0x65, 0x77, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0a,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x12, 0x13, 0x2e, 0x66, 0x6c, 0x6f,
	0x77, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x1a,
	0x14, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x6c, 0x6f,
	0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46,
	0x6c, 0x6f, 0x77, 0x12, 0x13, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x2e,
	0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c,
	0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f,
	0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_FlowService_proto_rawDescOnce sync.Once
	file_FlowService_proto_rawDescData = file_FlowService_proto_rawDesc
)

func file_FlowService_proto_rawDescGZIP() []byte {
	file_FlowService_proto_rawDescOnce.Do(func() {
		file_FlowService_proto_rawDescData = protoimpl.X.CompressGZIP(file_FlowService_proto_rawDescData)
	})
	return file_FlowService_proto_rawDescData
}

var file_FlowService_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_FlowService_proto_goTypes = []interface{}{
	(*RemoveFlowReq)(nil),   // 0: flow.RemoveFlowReq
	(*RemoveFlowResp)(nil),  // 1: flow.RemoveFlowResp
	(*UpdateFlowReq)(nil),   // 2: flow.UpdateFlowReq
	(*UpdateFlowResp)(nil),  // 3: flow.UpdateFlowResp
	(*NewFlowReq)(nil),      // 4: flow.NewFlowReq
	(*NewFlowResp)(nil),     // 5: flow.NewFlowResp
	(*GetFlowListReq)(nil),  // 6: flow.GetFlowListReq
	(*GetFlowListResp)(nil), // 7: flow.GetFlowListResp
	(*Flow)(nil),            // 8: flow.Flow
}
var file_FlowService_proto_depIdxs = []int32{
	8, // 0: flow.UpdateFlowReq.flow:type_name -> flow.Flow
	8, // 1: flow.NewFlowReq.flow:type_name -> flow.Flow
	8, // 2: flow.GetFlowListResp.flows:type_name -> flow.Flow
	4, // 3: flow.FlowService.NewFlow:input_type -> flow.NewFlowReq
	0, // 4: flow.FlowService.RemoveFlow:input_type -> flow.RemoveFlowReq
	2, // 5: flow.FlowService.UpdateFlow:input_type -> flow.UpdateFlowReq
	6, // 6: flow.FlowService.GetFlowList:input_type -> flow.GetFlowListReq
	5, // 7: flow.FlowService.NewFlow:output_type -> flow.NewFlowResp
	1, // 8: flow.FlowService.RemoveFlow:output_type -> flow.RemoveFlowResp
	3, // 9: flow.FlowService.UpdateFlow:output_type -> flow.UpdateFlowResp
	7, // 10: flow.FlowService.GetFlowList:output_type -> flow.GetFlowListResp
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_FlowService_proto_init() }
func file_FlowService_proto_init() {
	if File_FlowService_proto != nil {
		return
	}
	file_flowModels_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_FlowService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFlowReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FlowService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFlowResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FlowService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFlowReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FlowService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFlowResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FlowService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewFlowReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FlowService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewFlowResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FlowService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFlowListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FlowService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFlowListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_FlowService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_FlowService_proto_goTypes,
		DependencyIndexes: file_FlowService_proto_depIdxs,
		MessageInfos:      file_FlowService_proto_msgTypes,
	}.Build()
	File_FlowService_proto = out.File
	file_FlowService_proto_rawDesc = nil
	file_FlowService_proto_goTypes = nil
	file_FlowService_proto_depIdxs = nil
}
